<?php

namespace ControlBundle\Repository;

/**
 * MbLightSensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbLightSensorRepository extends \Doctrine\ORM\EntityRepository
{
}
