<?php

namespace ControlBundle\Repository;

/**
 * MbProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
