<?php

namespace ControlBundle\Repository;

/**
 * MbPumpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbPumpRepository extends \Doctrine\ORM\EntityRepository
{
}
