<?php

namespace ControlBundle\Repository;

/**
 * MbScheduleTimesheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbScheduleTimesheetRepository extends \Doctrine\ORM\EntityRepository
{
}
