<?php

namespace ControlBundle\Repository;

/**
 * MbSetupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbSetupRepository extends \Doctrine\ORM\EntityRepository
{
}
