<?php

namespace ControlBundle\Repository;

/**
 * MbSensorDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbSensorDataRepository extends \Doctrine\ORM\EntityRepository
{
    function getLastEntity() 
    {
        return $this->createQueryBuilder('e')->
        orderBy('e.date', 'DESC')->
        setMaxResults(1)->
        getQuery()->
        getOneOrNullResult();
  }
}
