<?php

namespace ControlBundle\Repository;

/**
 * MbValveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbValveRepository extends \Doctrine\ORM\EntityRepository
{
}
