<?php

namespace AppBundle\Repository;

/**
 * MbTemperatureSensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbTemperatureSensorRepository extends \Doctrine\ORM\EntityRepository
{
}
